/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import constants.Constants;
import db.SettingsLoader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Petar
 */
public class FKonfiguracijaServera extends javax.swing.JDialog {

    /**
     * Creates new form FKonfiguracijaPorta
     */
    public FKonfiguracijaServera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centrirajFormu();
        postaviTrenutnuVrednostParametara();
        postaviBojuPozadine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtServerPort = new javax.swing.JTextField();
        jBtnSacuvaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtMaxBrojKlijenata = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Port:");

        jBtnSacuvaj.setBackground(new java.awt.Color(51, 204, 255));
        jBtnSacuvaj.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Max broj klijenata:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnSacuvaj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtServerPort)
                            .addComponent(jTxtMaxBrojKlijenata, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtMaxBrojKlijenata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnSacuvaj)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed

        try {

            int port = Integer.parseInt(jTxtServerPort.getText().trim());

            if (port < 1 || port > 65535) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Za port je moguc unos samo celih brojeva od 1 do 65535 </font></html>");
                return;
            }

            int maxBrojKlijenata = Integer.parseInt(jTxtMaxBrojKlijenata.getText().trim());
            if (maxBrojKlijenata < 1 || maxBrojKlijenata > 20) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Za port je moguc unos samo celih brojeva od 1 do 65535 </font></html>");
                return;
            }

            SettingsLoader.getInstance().setValue(Constants.APPLICATION_PORT, String.valueOf(port));
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Promena parametara je uspesno zapamcena!</font></html>");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Za port je moguc unos samo celih brojeva od 1 do 65535. Broj klijenata </font></html>");

        }


    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtMaxBrojKlijenata;
    private javax.swing.JTextField jTxtServerPort;
    // End of variables declaration//GEN-END:variables

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void postaviTrenutnuVrednostParametara() {
        try {
            int port = Integer.parseInt(SettingsLoader.getInstance().getValue(Constants.APPLICATION_PORT));
            jTxtServerPort.setText(String.valueOf(port));

            int maxBrojKlijenata = Integer.parseInt(SettingsLoader.getInstance().getValue(Constants.MAX_CLIENTS));
            jTxtMaxBrojKlijenata.setText(String.valueOf(maxBrojKlijenata));
        } catch (Exception e) {
            System.out.println("Desila se greska prilikom ucitavanja vrednosti za port. Greska: " + e.getMessage());
        }

    }

    private void postaviBojuPozadine() {
        this.getContentPane().setBackground(new java.awt.Color(51, 0, 102));

    }

}
