/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import constants.Constants;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.text.IconView;
import db.SettingsLoader;

/**
 *
 * @author Petar
 */
public class FKonfiguracijaBaze extends javax.swing.JDialog {

    /**
     * Creates new form FKonfiguracija
     */
    public FKonfiguracijaBaze(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centrirajFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtDriver = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtUrl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jBtnTestKonekcija = new javax.swing.JButton();
        jBtnZapamtiKonekciju = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfiguracija");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Driver: ");

        jLabel2.setText("URL:");

        jLabel3.setText("Username: ");

        jLabel4.setText("Password:");

        jBtnTestKonekcija.setText("Test konekcije");
        jBtnTestKonekcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTestKonekcijaActionPerformed(evt);
            }
        });

        jBtnZapamtiKonekciju.setText("Sacuvaj");
        jBtnZapamtiKonekciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZapamtiKonekcijuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnTestKonekcija)
                        .addGap(132, 132, 132)
                        .addComponent(jBtnZapamtiKonekciju, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnZapamtiKonekciju)
                    .addComponent(jBtnTestKonekcija))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTestKonekcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTestKonekcijaActionPerformed

        String driver = jTxtDriver.getText().trim();
        String url = jTxtUrl.getText().trim();
        String username = jTxtUsername.getText().trim();
        String password = new String(jPassword.getPassword()).trim();

        try {
            Class.forName(driver);
            Connection connection = DriverManager.getConnection(url, username, password);
            JOptionPane.showMessageDialog(this, "Uspesno povezivanje sa bazom podataka!", "Uspesna konekcija", JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(this, "Driver nije odgovarajuci!", "Neuspesna konekcija", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "URL , username ili password nisu odgovarajucu!", "Neuspesna konekcija", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnTestKonekcijaActionPerformed

    private void jBtnZapamtiKonekcijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZapamtiKonekcijuActionPerformed

        String driver = jTxtDriver.getText().trim();
        String url = jTxtUrl.getText().trim();
        String username = jTxtUsername.getText().trim();
        String password = new String(jPassword.getPassword()).trim();

        try {
            SettingsLoader sl = SettingsLoader.getInstance();
            Class.forName(driver);
            Connection connection = DriverManager.getConnection(url, username, password);
            sl.setValue(Constants.DRIVER, driver);
            sl.setValue(Constants.URL, url);
            sl.setValue(Constants.USER, username);
            sl.setValue(Constants.PASSWORD, password);

            JOptionPane.showMessageDialog(this, "Uspesno povezivanje sa bazom podataka!Parametri su zapamceni", "Uspesna konekcija", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(this, "Driver nije odgovarajuci!", "Neuspesna konekcija", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "URL , username ili password nisu odgovarajucu!", "Neuspesna konekcija", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERROR![cannot load db.properties file]", "Neuspesna konekcija", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnZapamtiKonekcijuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            jTxtDriver.setText(SettingsLoader.getInstance().getValue(Constants.DRIVER));
            jTxtUrl.setText(SettingsLoader.getInstance().getValue(Constants.URL));
            jTxtUsername.setText(SettingsLoader.getInstance().getValue(Constants.USER));
            jPassword.setText(SettingsLoader.getInstance().getValue(Constants.PASSWORD));
        } catch (Exception e) {
            System.out.println("Dogodila se greska prilikom inicijalizovanja forme za knfiguraciju konekcije.Greska: "
                    + e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnTestKonekcija;
    private javax.swing.JButton jBtnZapamtiKonekciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTxtDriver;
    private javax.swing.JTextField jTxtUrl;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }
}
