/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.Korisnik;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import session.Session;

/**
 *
 * @author Petar
 */
public class FMain extends javax.swing.JFrame {

    private static FMain instance;

    /**
     * Creates new form FMain
     */
    private FMain() {
        initComponents();
        maksimizirajFormu();
        postaviStatusBar();
        onemoguciMenije();

    }

    public static FMain getInstance() {
        if (instance == null) {
            instance = new FMain();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovaniKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUdzbenik = new javax.swing.JMenu();
        jMenuKreirajUdzbenik = new javax.swing.JMenuItem();
        jMenuItemPretraziUdzbenik = new javax.swing.JMenuItem();
        jMenuPredmet = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuPretrazi = new javax.swing.JMenuItem();
        jMenuAutor = new javax.swing.JMenu();
        jMenuPristupSistemu = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");
        setResizable(false);

        jLabel1.setText("Ulogovani korisnik:");

        jLabelUlogovaniKorisnik.setText(" ");

        jMenuUdzbenik.setText("Udzbenik");

        jMenuKreirajUdzbenik.setText("Kreiraj");
        jMenuKreirajUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKreirajUdzbenikActionPerformed(evt);
            }
        });
        jMenuUdzbenik.add(jMenuKreirajUdzbenik);

        jMenuItemPretraziUdzbenik.setText("Pretrazi");
        jMenuItemPretraziUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziUdzbenikActionPerformed(evt);
            }
        });
        jMenuUdzbenik.add(jMenuItemPretraziUdzbenik);

        jMenuBar1.add(jMenuUdzbenik);

        jMenuPredmet.setText("Predmet");

        jMenuItem1.setText("Kreiraj");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuPredmet.add(jMenuItem1);

        jMenuPretrazi.setText("Pretrazi");
        jMenuPredmet.add(jMenuPretrazi);

        jMenuBar1.add(jMenuPredmet);

        jMenuAutor.setText("O autoru");
        jMenuBar1.add(jMenuAutor);

        jMenuPristupSistemu.setText("Pristup sistemu");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuPristupSistemu.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuPristupSistemu.add(jMenuItemLogout);

        jMenuBar1.add(jMenuPristupSistemu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1150, 1150, 1150)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUlogovaniKorisnik))
                .addGap(265, 265, 265))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKreirajUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKreirajUdzbenikActionPerformed
        JDialog fUdzbenik = new FUdzbenik(this, true);
        fUdzbenik.setVisible(true);

        statusLabel.setText("Use case: Kreiranje udzbenika!");
    }//GEN-LAST:event_jMenuKreirajUdzbenikActionPerformed

    private void jMenuItemPretraziUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziUdzbenikActionPerformed
        JDialog fSelectUdzbenik = new FSelectUdzbenik(this, true);
        fSelectUdzbenik.setVisible(true);

        statusLabel.setText("Use case: Pretrazivanje udzbenika!");
    }//GEN-LAST:event_jMenuItemPretraziUdzbenikActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialog fPredmet = new FPredmet(this, true, this);
        fPredmet.setVisible(true);

        statusLabel.setText("Use case: Kreiranje predmeta!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        JDialog fLogin = new FLogin(this, true);
        fLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        if (Session.getInstance().getMap().containsKey("ulogovani_korisnik")) {
            Session.getInstance().getMap().remove("ulogovani_korisnik");
            onemoguciMenijeLogout();
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUlogovaniKorisnik;
    private javax.swing.JMenu jMenuAutor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPretraziUdzbenik;
    private javax.swing.JMenuItem jMenuKreirajUdzbenik;
    private javax.swing.JMenu jMenuPredmet;
    private javax.swing.JMenuItem jMenuPretrazi;
    private javax.swing.JMenu jMenuPristupSistemu;
    private javax.swing.JMenu jMenuUdzbenik;
    // End of variables declaration//GEN-END:variables
    private JPanel statusPanel;
    private JLabel statusLabel;

    private void maksimizirajFormu() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void postaviStatusBar() {
        setLayout(new BorderLayout());

        statusPanel = new JPanel();
        statusPanel.setBorder(new BevelBorder(BevelBorder.LOWERED));
        add(statusPanel, BorderLayout.SOUTH);

        statusPanel.setPreferredSize(new Dimension(getWidth(), 30));
        statusPanel.setLayout(new BoxLayout(statusPanel, BoxLayout.X_AXIS));
        statusLabel = new JLabel("Status: This is main form!");
        statusLabel.setHorizontalAlignment(SwingConstants.LEFT);
        statusPanel.add(statusLabel);
    }

    public void postaviUlogovanogKorisnika() {
        try {
            if (Session.getInstance().getMap().containsKey("ulogovani_korisnik")) {
                Korisnik korisnik = (Korisnik) Session.getInstance().getMap().get("ulogovani_korisnik");
                jLabelUlogovaniKorisnik.setText(korisnik.getIme() + " " + korisnik.getPrezime());
            } else {
                jLabelUlogovaniKorisnik.setText("-");
            }
        } catch (Exception e) {
            System.out.println("Dogodila se greska prilikom postavljanja ulogovanog korisnika. Greska:" + e.getMessage());
        }
    }

    public void omoguciMenije() {
        jMenuPredmet.setEnabled(true);
        jMenuUdzbenik.setEnabled(true);
        jMenuPristupSistemu.setEnabled(true);

        jMenuAutor.setEnabled(true);
        jMenuItemLogin.setEnabled(false);
        jMenuItemLogout.setEnabled(true);

    }

    private void onemoguciMenije() {
        try {
            jMenuPredmet.setEnabled(false);
            jMenuUdzbenik.setEnabled(false);

            jMenuPristupSistemu.setEnabled(true);
            jMenuItemLogout.setEnabled(false);
            jMenuAutor.setEnabled(false);

        } catch (Exception e) {
            System.out.println("Dogodila se greska prilikom onemogucivanja menija");
        }
    }

    void omoguciPristupSistemu() {
        jMenuPristupSistemu.setEnabled(true);
        jMenuItemLogin.setEnabled(true);
        jMenuItemLogout.setEnabled(false);
    }

    private void onemoguciMenijeLogout() {
        jMenuPredmet.setEnabled(false);
        jMenuUdzbenik.setEnabled(false);

        jMenuItemLogin.setEnabled(true);
        jMenuItemLogout.setEnabled(false);
    }

}
