/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.Nastavnik;
import domen.NastavnikNaPredmetu;
import domen.Predmet;
import domen.TematskaCelina;
import domen.TipNastave;
import domen.Udzbenik;
import domen.VrstaINivoStudija;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import kontroler.Kontroler;
import renderer.NastavnikRenderer;
import renderer.TipNastaveRenderer;
import renderer.UdzbenikRenderer;
import renderer.VrstaINivoStudijaRenderer;
import session.Session;
import table.model.NastavnikNaPredmetuTableModel;
import table.model.UdzbenikSkraceniTableModel;
import transfer.util.IOperation;

/**
 *
 * @author Petar
 */
public class FPredmet extends javax.swing.JFrame {

    JFrame fMain;
    private Predmet predmetZaPregledanje;

    /**
     * Creates new form FPredmet
     */
    public FPredmet(FMain fMain) {
        initComponents();
        centrirajFormu();
        maksimizirajFormu();
        this.fMain = fMain;
        popuniVrstaINivoStudijaCombo();
        popuniNastavniciCombo();
        popuniUdzbeniciCombo();
        popuniTipNastaveCombo();
        inicijalizujTabeluNastavniciNaPredmetu();
        inicijalizujTabeluUdzbenik();
        pripremiFormu(FormMode.NEW);
        postaviBojuPozadine();
    }

    public FPredmet(FMain fMain, int predmetId) {
        initComponents();
        centrirajFormu();
        maksimizirajFormu();
        this.fMain = fMain;
        popuniFormuZaPredmet(predmetId);
        pripremiFormu(FormMode.VIEW);
        postaviBojuPozadine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtPredmetId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNazivPredmeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtUslov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCilj = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaIshod = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jComboVrstaINivoStudija = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtDrugiObliciNastave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtStudijskiIstrazivackiRad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboIzborNastavnika = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboTipNastave = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblNastavnici = new javax.swing.JTable();
        jBtnDodajNastavnika = new javax.swing.JButton();
        jBtnObrisiNastavnika = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JComboUdzbenik = new javax.swing.JComboBox<>();
        jBtnDodajUdzbenik = new javax.swing.JButton();
        jBtnObrisiUdzbenik = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblUdzbenici = new javax.swing.JTable();
        jBtnObrisi = new javax.swing.JButton();
        jBtnSacuvaj = new javax.swing.JButton();
        jBtnAzuriraj = new javax.swing.JButton();
        jSpinnerBrCasovaPredavanjaNedeljno = new javax.swing.JSpinner();
        jSpinnerBrCasovaVezbiNedeljno = new javax.swing.JSpinner();
        jSpinnerOstaliCasovi = new javax.swing.JSpinner();
        jBtnUnosSadrzajaTekst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Predmet");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id:");

        jTxtPredmetId.setEditable(false);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Naziv:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Uslov:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cilj: ");

        jTextAreaCilj.setColumns(20);
        jTextAreaCilj.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCilj);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ishod:");

        jTextAreaIshod.setColumns(20);
        jTextAreaIshod.setRows(5);
        jScrollPane2.setViewportView(jTextAreaIshod);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vrsta i nivo studija:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Br. casova predavanja nedeljno:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Br. casova vezbi nedeljno:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ostali casovi: ");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Drugi oblici nastave: ");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Studijski istrazivacki rad:");

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nastavnik", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Izaberite nastavnika:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Odaberite tip nastave:");

        jTblNastavnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTblNastavnici);

        jBtnDodajNastavnika.setBackground(new java.awt.Color(51, 204, 255));
        jBtnDodajNastavnika.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDodajNastavnika.setText("+");
        jBtnDodajNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajNastavnikaActionPerformed(evt);
            }
        });

        jBtnObrisiNastavnika.setBackground(new java.awt.Color(51, 204, 255));
        jBtnObrisiNastavnika.setForeground(new java.awt.Color(255, 255, 255));
        jBtnObrisiNastavnika.setText("-");
        jBtnObrisiNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiNastavnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboIzborNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTipNastave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDodajNastavnika, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnObrisiNastavnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipNastave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboIzborNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnDodajNastavnika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnObrisiNastavnika))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Udzbenik", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        JComboUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboUdzbenikActionPerformed(evt);
            }
        });

        jBtnDodajUdzbenik.setBackground(new java.awt.Color(51, 204, 255));
        jBtnDodajUdzbenik.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDodajUdzbenik.setText("+");
        jBtnDodajUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajUdzbenikActionPerformed(evt);
            }
        });

        jBtnObrisiUdzbenik.setBackground(new java.awt.Color(51, 204, 255));
        jBtnObrisiUdzbenik.setForeground(new java.awt.Color(255, 255, 255));
        jBtnObrisiUdzbenik.setText("-");
        jBtnObrisiUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiUdzbenikActionPerformed(evt);
            }
        });

        jTblUdzbenici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTblUdzbenici);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JComboUdzbenik, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDodajUdzbenik, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnObrisiUdzbenik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JComboUdzbenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnDodajUdzbenik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnObrisiUdzbenik)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBtnObrisi.setText("Obrisi");
        jBtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiActionPerformed(evt);
            }
        });

        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jBtnAzuriraj.setText("Azuriraj");
        jBtnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAzurirajActionPerformed(evt);
            }
        });

        jBtnUnosSadrzajaTekst.setBackground(new java.awt.Color(51, 204, 255));
        jBtnUnosSadrzajaTekst.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUnosSadrzajaTekst.setText("Kliknite za unos sadrzaja");
        jBtnUnosSadrzajaTekst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUnosSadrzajaTekstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnUnosSadrzajaTekst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(646, 646, 646))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtStudijskiIstrazivackiRad)
                                            .addComponent(jTxtDrugiObliciNastave))
                                        .addGap(113, 113, 113))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerBrCasovaPredavanjaNedeljno, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(jSpinnerBrCasovaVezbiNedeljno)
                                            .addComponent(jSpinnerOstaliCasovi))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(76, 76, 76)
                                                    .addComponent(jComboVrstaINivoStudija, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTxtUslov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTxtNazivPredmeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTxtPredmetId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jBtnSacuvaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnAzuriraj)
                                .addGap(102, 102, 102)
                                .addComponent(jBtnObrisi))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtPredmetId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTxtUslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboVrstaINivoStudija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jSpinnerBrCasovaPredavanjaNedeljno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSpinnerBrCasovaVezbiNedeljno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jSpinnerOstaliCasovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTxtDrugiObliciNastave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTxtStudijskiIstrazivackiRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jBtnUnosSadrzajaTekst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnObrisi)
                    .addComponent(jBtnAzuriraj)
                    .addComponent(jBtnSacuvaj))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDodajNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajNastavnikaActionPerformed
        try {
            NastavnikNaPredmetuTableModel nnptm = (NastavnikNaPredmetuTableModel) jTblNastavnici.getModel();
            Nastavnik nastavnik = (Nastavnik) jComboIzborNastavnika.getSelectedItem();
            TipNastave tipNastave = (TipNastave) jComboTipNastave.getSelectedItem();

            nnptm.dodajNastavnikaNaPredmet(nastavnik, tipNastave, predmetZaPregledanje);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom dodavanja novog nastavnika u tabelu za predmet .Greska:" + e.getMessage()+"</font></html>");
        }
    }//GEN-LAST:event_jBtnDodajNastavnikaActionPerformed

    private void jBtnObrisiNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiNastavnikaActionPerformed
        try {
            int selektovaniRed = jTblNastavnici.getSelectedRow();

            if (selektovaniRed >= 0) {
                NastavnikNaPredmetuTableModel nnptm = (NastavnikNaPredmetuTableModel) jTblNastavnici.getModel();
                nnptm.obrisiNastavnikaSaPredmeta(selektovaniRed);
            } else {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Niste selektovali red brisanje</font></html>");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom brisanja  nastavnika iz tabele za predmet .Greska:" + e.getMessage()+"</font></html>");

        }
    }//GEN-LAST:event_jBtnObrisiNastavnikaActionPerformed

    private void jBtnDodajUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajUdzbenikActionPerformed
        try {
            UdzbenikSkraceniTableModel ustm = (UdzbenikSkraceniTableModel) jTblUdzbenici.getModel();
            Udzbenik udzbenik = (Udzbenik) JComboUdzbenik.getSelectedItem();
            ustm.dodajUdzbenik(udzbenik);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom dodavanja novog udzbenika u tabelu za predmet .Greska:" + e.getMessage()+"</font></html>");
        }
    }//GEN-LAST:event_jBtnDodajUdzbenikActionPerformed

    private void jBtnObrisiUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiUdzbenikActionPerformed
        try {
            int selektovaniRed = jTblUdzbenici.getSelectedRow();

            if (selektovaniRed >= 0) {
                UdzbenikSkraceniTableModel ustm = (UdzbenikSkraceniTableModel) jTblUdzbenici.getModel();
                ustm.obrisiNastavnikaSaPredmeta(selektovaniRed);
            } else {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Niste selektovali red brisanje</font></html>");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom brisanja  nastavnika iz tabele za predmet .Greska:" + e.getMessage()+"</font></html>");

        }
    }//GEN-LAST:event_jBtnObrisiUdzbenikActionPerformed

    private void jBtnUnosSadrzajaTekstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUnosSadrzajaTekstActionPerformed
        JDialog fSadrzajTekst = new FSadrzajTekst(this, true);
        fSadrzajTekst.setVisible(true);
    }//GEN-LAST:event_jBtnUnosSadrzajaTekstActionPerformed

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {

            String naziv = jTxtNazivPredmeta.getText().trim();

            if (naziv.length() == 0) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Morate uneti naziv predmeta!</font></html>");
                return;
            }

            String uslov = jTxtUslov.getText().trim();

            String cilj = jTextAreaCilj.getText().trim();

            String ishod = jTextAreaIshod.getText().trim();

            VrstaINivoStudija vrstaINivoStudija = (VrstaINivoStudija) jComboVrstaINivoStudija.getSelectedItem();

            int brCasovaPredavanjaNedeljno;
            try {
                jSpinnerBrCasovaPredavanjaNedeljno.commitEdit();

                brCasovaPredavanjaNedeljno = (Integer) jSpinnerBrCasovaPredavanjaNedeljno.getValue();
                if (brCasovaPredavanjaNedeljno < 0) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Moguc je izbor samo nenegativnih brojeva!</font></html>");
                return;
            }

            int brCasovaVezbiNedeljno;
            try {
                jSpinnerBrCasovaVezbiNedeljno.commitEdit();
                brCasovaVezbiNedeljno = (Integer) jSpinnerBrCasovaVezbiNedeljno.getValue();
                if (brCasovaVezbiNedeljno < 0) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Moguc je izbor samo nenegativnih brojeva!");
                return;
            }

            int ostaliCasovi;
            try {
                jSpinnerOstaliCasovi.commitEdit();
                ostaliCasovi = (Integer) jSpinnerOstaliCasovi.getValue();
                if (ostaliCasovi < 0) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Moguc je izbor samo nenegativnih brojeva!</font></html>");
                return;
            }

            String drugiObliciNastave = jTxtDrugiObliciNastave.getText().trim();

            String studijskiIstrazivackiRad = jTxtStudijskiIstrazivackiRad.getText().trim();

            //   List<TematskaCelina> tematskeCelineStruktura = Session.getInstance().getTematskeCelineStruktura();
            String tematskeCelineTekst = Session.getInstance().getTematskeCelineTekst();

            NastavnikNaPredmetuTableModel nnptm = (NastavnikNaPredmetuTableModel) jTblNastavnici.getModel();
            List<NastavnikNaPredmetu> nastavniciNaPredmetu = nnptm.getNastavniciNaPredmetu();

            UdzbenikSkraceniTableModel ustm = (UdzbenikSkraceniTableModel) jTblUdzbenici.getModel();
            List<Udzbenik> udzbenici = ustm.getUdzbenici();

            Predmet predmet = new Predmet();
            predmet.setNaziv(naziv);
            predmet.setUslov(uslov);
            predmet.setCilj(cilj);
            predmet.setIshod(ishod);
            predmet.setVrstaINivoStudija(vrstaINivoStudija);
            predmet.setBrCasovaPredavanjaNedeljno(brCasovaPredavanjaNedeljno);
            predmet.setBrCasovaVezbiNedeljno(brCasovaVezbiNedeljno);
            predmet.setDrugiObliciNastave(drugiObliciNastave);
            predmet.setStudijskiIstrazivackiRad(studijskiIstrazivackiRad);
            predmet.setSadrzajTekst(tematskeCelineTekst);
            //predmet.setSadrzajTematskeCeline(tematskeCelineStruktura);
            predmet.setNastavnici(nastavniciNaPredmetu);
            predmet.setUdzbenici(udzbenici);

            Kontroler.getInstance().posaljiZahtev(IOperation.KREIRAJ_PREDMET, predmet);
            Predmet kreiraniPredmet = (Predmet) Kontroler.getInstance().primiOdgovor();

            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Predmet :" + kreiraniPredmet.getNaziv() + " je uspesno sacuvan u bazi podataka!</font></html>");

            dispose();

            JDialog fSelecetPredmet = new FSelectPredmet(fMain, true);
            fSelecetPredmet.setVisible(true);
            Session.getInstance().setTematskeCelineTekst("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"<html><font color=#ffffff>" + e.getMessage() + "</font></html>");
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void JComboUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboUdzbenikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboUdzbenikActionPerformed

    private void jBtnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAzurirajActionPerformed
        try {
            int predmetId;
            try {
                predmetId = Integer.parseInt(jTxtPredmetId.getText().trim());

                if (predmetId < 0) {
                    throw new Exception();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>PredmetId mora biti ceo nenegativan broj!</font></html>");
                return;
            }

            String naziv = jTxtNazivPredmeta.getText().trim();

            if (naziv.length() == 0) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Morate uneti naziv predmeta!</font></html>");
                return;
            }

            String uslov = jTxtUslov.getText().trim();

            String cilj = jTextAreaCilj.getText().trim();

            String ishod = jTextAreaIshod.getText().trim();

            VrstaINivoStudija vrstaINivoStudija = (VrstaINivoStudija) jComboVrstaINivoStudija.getSelectedItem();

            int brCasovaPredavanjaNedeljno;
            try {
                jSpinnerBrCasovaPredavanjaNedeljno.commitEdit();

                brCasovaPredavanjaNedeljno = (Integer) jSpinnerBrCasovaPredavanjaNedeljno.getValue();
                if (brCasovaPredavanjaNedeljno < 0) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Moguc je izbor samo nenegativnih brojeva!</font></html>");
                return;
            }

            int brCasovaVezbiNedeljno;
            try {
                jSpinnerBrCasovaVezbiNedeljno.commitEdit();
                brCasovaVezbiNedeljno = (Integer) jSpinnerBrCasovaVezbiNedeljno.getValue();
                if (brCasovaVezbiNedeljno < 0) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Moguc je izbor samo nenegativnih brojeva!</font></html>");
                return;
            }

            int ostaliCasovi;
            try {
                jSpinnerOstaliCasovi.commitEdit();
                ostaliCasovi = (Integer) jSpinnerOstaliCasovi.getValue();
                if (ostaliCasovi < 0) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Moguc je izbor samo nenegativnih brojeva!</font></html>");
                return;
            }

            String drugiObliciNastave = jTxtDrugiObliciNastave.getText().trim();

            String studijskiIstrazivackiRad = jTxtStudijskiIstrazivackiRad.getText().trim();

            // List<TematskaCelina> tematskeCelineStruktura = Session.getInstance().getTematskeCelineStruktura();
            String tematskeCelineTekst = Session.getInstance().getTematskeCelineTekst();

            NastavnikNaPredmetuTableModel nnptm = (NastavnikNaPredmetuTableModel) jTblNastavnici.getModel();
            List<NastavnikNaPredmetu> nastavniciNaPredmetu = nnptm.getNastavniciNaPredmetu();

            UdzbenikSkraceniTableModel ustm = (UdzbenikSkraceniTableModel) jTblUdzbenici.getModel();
            List<Udzbenik> udzbenici = ustm.getUdzbenici();

            Predmet predmet = new Predmet();

            predmet.setPredmetId(predmetId);
            predmet.setNaziv(naziv);
            predmet.setUslov(uslov);
            predmet.setCilj(cilj);
            predmet.setIshod(ishod);
            predmet.setVrstaINivoStudija(vrstaINivoStudija);
            predmet.setBrCasovaPredavanjaNedeljno(brCasovaPredavanjaNedeljno);
            predmet.setBrCasovaVezbiNedeljno(brCasovaVezbiNedeljno);
            predmet.setDrugiObliciNastave(drugiObliciNastave);
            predmet.setStudijskiIstrazivackiRad(studijskiIstrazivackiRad);
            predmet.setSadrzajTekst(tematskeCelineTekst);
            // predmet.setSadrzajTematskeCeline(tematskeCelineStruktura);
            predmet.setNastavnici(nastavniciNaPredmetu);
            predmet.setUdzbenici(udzbenici);

            Kontroler.getInstance().posaljiZahtev(IOperation.AZURIRAJ_PREDMET, predmet);
            Predmet kreiraniPredmet = (Predmet) Kontroler.getInstance().primiOdgovor();

            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Predmet : " + kreiraniPredmet.getNaziv() + " je uspesno azuriran!</font></html>");
            dispose();

            Session.getInstance().setTematskeCelineTekst("");

            JDialog fSelecetPredmet = new FSelectPredmet(fMain, true);
            fSelecetPredmet.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom azuriranja predmeta! Greska:" + e.getMessage()+"</font></html>");
        }
    }//GEN-LAST:event_jBtnAzurirajActionPerformed

    private void jBtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiActionPerformed
        int predmetId;
        try {
            predmetId = Integer.parseInt(jTxtPredmetId.getText().trim());

            if (predmetId < 0) {
                throw new Exception();
            }
            JDialog fPotvrdaBrisanjaPredmeta = new FPotvrdaBrisanjaPredmeta(this, true, predmetId);
            fPotvrdaBrisanjaPredmeta.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>PredmetId mora biti ceo nenegativan broj!</font></html>");
            return;
        }

    }//GEN-LAST:event_jBtnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> JComboUdzbenik;
    private javax.swing.JButton jBtnAzuriraj;
    private javax.swing.JButton jBtnDodajNastavnika;
    private javax.swing.JButton jBtnDodajUdzbenik;
    private javax.swing.JButton jBtnObrisi;
    private javax.swing.JButton jBtnObrisiNastavnika;
    private javax.swing.JButton jBtnObrisiUdzbenik;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JButton jBtnUnosSadrzajaTekst;
    private javax.swing.JComboBox<Object> jComboIzborNastavnika;
    private javax.swing.JComboBox<Object> jComboTipNastave;
    private javax.swing.JComboBox<Object> jComboVrstaINivoStudija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerBrCasovaPredavanjaNedeljno;
    private javax.swing.JSpinner jSpinnerBrCasovaVezbiNedeljno;
    private javax.swing.JSpinner jSpinnerOstaliCasovi;
    private javax.swing.JTable jTblNastavnici;
    private javax.swing.JTable jTblUdzbenici;
    private javax.swing.JTextArea jTextAreaCilj;
    private javax.swing.JTextArea jTextAreaIshod;
    private javax.swing.JTextField jTxtDrugiObliciNastave;
    private javax.swing.JTextField jTxtNazivPredmeta;
    private javax.swing.JTextField jTxtPredmetId;
    private javax.swing.JTextField jTxtStudijskiIstrazivackiRad;
    private javax.swing.JTextField jTxtUslov;
    // End of variables declaration//GEN-END:variables

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void popuniVrstaINivoStudijaCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_VRSTE_I_NIVOE_STUDIJA, null);
            List<VrstaINivoStudija> vrsteStudija = (List<VrstaINivoStudija>) Kontroler.getInstance().primiOdgovor();

            for (VrstaINivoStudija vins : vrsteStudija) {
                jComboVrstaINivoStudija.addItem(vins);
            }

            jComboVrstaINivoStudija.setRenderer(new VrstaINivoStudijaRenderer());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"<html><font color=#ffffff>" + e.getMessage() + "</font></html>");
        }
    }

    private void popuniNastavniciCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_NASTAVNIKE, null);
            List<Nastavnik> nastavnici = (List<Nastavnik>) Kontroler.getInstance().primiOdgovor();

            for (Nastavnik nastavnik : nastavnici) {
                jComboIzborNastavnika.addItem(nastavnik);
            }

            jComboIzborNastavnika.setRenderer(new NastavnikRenderer());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom inicijalizacije combobox-a za nastavnike.Greska:" + e.getMessage()+"</font></html>");

        }
    }

    private void popuniUdzbeniciCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_UDZBENIKE, null);
            List<Udzbenik> udzbenici = (List<Udzbenik>) Kontroler.getInstance().primiOdgovor();

            for (Udzbenik udzbenik : udzbenici) {
                JComboUdzbenik.addItem(udzbenik);
            }
            JComboUdzbenik.setRenderer(new UdzbenikRenderer());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom inicijalizacije combobox-a za udzbenike.Greska:" + e.getMessage()+"</font></html>");

        }
    }

    private void inicijalizujTabeluNastavniciNaPredmetu() {
        try {

            TableModel nnptm = new NastavnikNaPredmetuTableModel(new ArrayList());
            jTblNastavnici.setModel(nnptm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom inicijalizacije table modela za nastavnike na predmetu.Greska:" + e.getMessage()+"</font></html>");

        }
    }

    private void inicijalizujTabeluUdzbenik() {
        try {
            TableModel ustm = new UdzbenikSkraceniTableModel(new ArrayList<>());
            jTblUdzbenici.setModel(ustm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom inicijalizacije table modela za udzbenik.Greska:" + e.getMessage()+"</font></html>");

        }
    }

    private void maksimizirajFormu() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void pripremiFormu(FormMode formMode) {
        switch (formMode) {
            case NEW:
                jBtnObrisi.setEnabled(false);
                jBtnAzuriraj.setEnabled(false);
                jBtnSacuvaj.setEnabled(true);

                jBtnSacuvaj.setForeground(Color.white);
                jBtnSacuvaj.setBackground(Color.green);

                break;
            case VIEW:
                jBtnObrisi.setEnabled(true);
                jBtnAzuriraj.setEnabled(true);
                jBtnSacuvaj.setEnabled(false);
                jTxtPredmetId.setEnabled(false);

                jBtnObrisi.setBackground(Color.red);
                jBtnObrisi.setForeground(Color.white);

                jBtnAzuriraj.setBackground(Color.yellow);
                jBtnObrisi.setForeground(Color.white);
                break;

        }
    }

    private void popuniFormuZaPredmet(int predmetId) {
        try {

            Kontroler.getInstance().posaljiZahtev(IOperation.PRONADJI_PREDMET_PO_ID, predmetId);
            Predmet predmet = (Predmet) Kontroler.getInstance().primiOdgovor();

            jTxtPredmetId.setText(String.valueOf(predmet.getPredmetId()));
            jTxtNazivPredmeta.setText(predmet.getNaziv());
            jSpinnerBrCasovaPredavanjaNedeljno.setValue(predmet.getBrCasovaPredavanjaNedeljno());
            jSpinnerBrCasovaVezbiNedeljno.setValue(predmet.getBrCasovaVezbiNedeljno());
            jSpinnerOstaliCasovi.setValue(predmet.getOstaliCasovi());
            jTxtDrugiObliciNastave.setText(predmet.getDrugiObliciNastave());
            jTxtStudijskiIstrazivackiRad.setText(predmet.getStudijskiIstrazivackiRad());
            jTextAreaCilj.setText(predmet.getCilj());
            jTextAreaIshod.setText(predmet.getIshod());
            jTxtUslov.setText(predmet.getUslov());

            TableModel utm = new UdzbenikSkraceniTableModel(predmet.getUdzbenici());
            jTblUdzbenici.setModel(utm);

            TableModel nnptm = new NastavnikNaPredmetuTableModel(predmet.getNastavnici());
            jTblNastavnici.setModel(nnptm);
            popuniNastavniciCombo();
            popuniUdzbeniciCombo();
            popuniTipNastaveCombo();
            popuniVrstaINivoStudijaCombo();

            jComboVrstaINivoStudija.setSelectedItem(predmet.getVrstaINivoStudija());
            predmetZaPregledanje = predmet;

            Session.getInstance().setTematskeCelineTekst(predmet.getSadrzajTekst());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom postavljanja predmeta.Greska:" + e.getMessage()+"</font></html>");
        }
    }

    private void popuniTipNastaveCombo() {

        try {

            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_TIPOVE_NASTAVE, null);

            List<TipNastave> tipoviNastave = (List<TipNastave>) Kontroler.getInstance().primiOdgovor();

            for (TipNastave tipNastave : tipoviNastave) {

                jComboTipNastave.addItem(tipNastave);

            }

            jComboTipNastave.setRenderer(new TipNastaveRenderer());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Dogodila se greska prilikom inicijalizacije combobox-a za tipove nastave.Greska:" + e.getMessage()+"</font></html>");

        }

    }

    private void postaviBojuPozadine() {
        this.getContentPane().setBackground(new java.awt.Color(51, 0, 102));
    }

}
