/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.Nastavnik;
import domen.TipNastave;
import domen.Udzbenik;
import domen.VrstaINivoStudija;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import kontroler.Kontroler;
import renderer.NastavnikRenderer;
import renderer.TipNastaveRenderer;
import renderer.UdzbenikRenderer;
import renderer.VrstaINivoStudijaRenderer;
import table.model.NastavnikNaPredmetuTableModel;
import transfer.util.IOperation;

/**
 *
 * @author Petar
 */
public class FPredmet extends javax.swing.JDialog {

    JFrame fMain;

    /**
     * Creates new form FPredmet
     */
    public FPredmet(java.awt.Frame parent, boolean modal, FMain fMain) {
        super(parent, modal);
        initComponents();
        centrirajFormu();
        this.fMain = fMain;
        popuniVrstaINivoStudijaCombo();
        popuniTipNastaveCombo();
        popuniNastavniciCombo();
        popuniUdzbeniciCombo();
        inicijalizujTabeluNastavniciNaPredmetu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtUdzbenikId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNazivPredmeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtUslov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCilj = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaIshod = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jComboVrstaINivoStudija = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtDrugiObliciNastave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtStudijskiIstrazivackiRad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboIzborNastavnika = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboTipNastave = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblNastavnici = new javax.swing.JTable();
        jBtnDodajNastavnika = new javax.swing.JButton();
        jBtnObrisiNastavnika = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JComboUdzbenik = new javax.swing.JComboBox<>();
        jBtnDodajUdzbenik = new javax.swing.JButton();
        jBtnObrisiUdzbenik = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblUdzbenici = new javax.swing.JTable();
        jBtnNoviUdzbenik = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBtnUnosSadrzajaTekst = new javax.swing.JButton();
        jBtnUnosStruktuiraniOblik = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboTipNastaveSadrzaj = new javax.swing.JComboBox<>();
        jBtnObrisi = new javax.swing.JButton();
        jBtnSacuvaj = new javax.swing.JButton();
        jBtnAzuriraj = new javax.swing.JButton();
        jLabelRezultatPretrage = new javax.swing.JLabel();
        jSpinnerBrCasovaPredavanjaNedeljno = new javax.swing.JSpinner();
        jSpinnerBrCasovaVezbiNedeljno = new javax.swing.JSpinner();
        jSpinnerOstaliCasovi = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Predmet");

        jLabel1.setText("Id:");

        jTxtUdzbenikId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtUdzbenikIdFocusLost(evt);
            }
        });

        jLabel2.setText("Naziv:");

        jLabel3.setText("Uslov:");

        jLabel4.setText("Cilj: ");

        jTextAreaCilj.setColumns(20);
        jTextAreaCilj.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCilj);

        jLabel5.setText("Ishod:");

        jTextAreaIshod.setColumns(20);
        jTextAreaIshod.setRows(5);
        jScrollPane2.setViewportView(jTextAreaIshod);

        jLabel6.setText("Vrsta i nivo studija:");

        jLabel7.setText("Br. casova predavanja nedeljno:");

        jLabel8.setText("Br. casova vezbi nedeljno:");

        jLabel9.setText("Ostali casovi: ");

        jLabel10.setText("Drugi oblici nastave: ");

        jLabel11.setText("Studijski istrazivacki rad:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nastavnik"));

        jLabel12.setText("Izaberite nastavnika:");

        jLabel13.setText("Odaberite tip nastave:");

        jTblNastavnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTblNastavnici);

        jBtnDodajNastavnika.setText("+");
        jBtnDodajNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajNastavnikaActionPerformed(evt);
            }
        });

        jBtnObrisiNastavnika.setText("-");
        jBtnObrisiNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiNastavnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboIzborNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTipNastave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDodajNastavnika, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnObrisiNastavnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipNastave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboIzborNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnDodajNastavnika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnObrisiNastavnika))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Udzbenik"));

        JComboUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboUdzbenikActionPerformed(evt);
            }
        });

        jBtnDodajUdzbenik.setText("+");
        jBtnDodajUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajUdzbenikActionPerformed(evt);
            }
        });

        jBtnObrisiUdzbenik.setText("-");
        jBtnObrisiUdzbenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiUdzbenikActionPerformed(evt);
            }
        });

        jTblUdzbenici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTblUdzbenici);

        jBtnNoviUdzbenik.setText("Unesite udzbenik");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JComboUdzbenik, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnNoviUdzbenik, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDodajUdzbenik, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnObrisiUdzbenik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboUdzbenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNoviUdzbenik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnDodajUdzbenik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnObrisiUdzbenik)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sadrzaj "));

        jBtnUnosSadrzajaTekst.setText("Unos u tekstualnom obliku");
        jBtnUnosSadrzajaTekst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUnosSadrzajaTekstActionPerformed(evt);
            }
        });

        jBtnUnosStruktuiraniOblik.setText("Unos u struktuiranom obliku");
        jBtnUnosStruktuiraniOblik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUnosStruktuiraniOblikActionPerformed(evt);
            }
        });

        jLabel14.setText("Izaberite tip nastave:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBtnUnosStruktuiraniOblik, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jBtnUnosSadrzajaTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(28, 28, 28)
                        .addComponent(jComboTipNastaveSadrzaj, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboTipNastaveSadrzaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUnosStruktuiraniOblik)
                    .addComponent(jBtnUnosSadrzajaTekst))
                .addContainerGap())
        );

        jBtnObrisi.setText("Obrisi");

        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jBtnAzuriraj.setText("Azuriraj");

        jLabelRezultatPretrage.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtStudijskiIstrazivackiRad)
                                            .addComponent(jTxtDrugiObliciNastave))
                                        .addGap(155, 155, 155))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerBrCasovaPredavanjaNedeljno, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(jSpinnerBrCasovaVezbiNedeljno)
                                            .addComponent(jSpinnerOstaliCasovi))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(75, 75, 75)
                                                    .addComponent(jComboVrstaINivoStudija, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                                        .addComponent(jTxtUslov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                                        .addComponent(jTxtNazivPredmeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                                        .addComponent(jTxtUdzbenikId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                                        .addComponent(jLabelRezultatPretrage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                    .addComponent(jLabel11)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnAzuriraj)
                        .addGap(83, 83, 83)
                        .addComponent(jBtnSacuvaj)
                        .addGap(67, 67, 67)
                        .addComponent(jBtnObrisi)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtUdzbenikId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabelRezultatPretrage)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtUslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jComboVrstaINivoStudija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jSpinnerBrCasovaPredavanjaNedeljno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSpinnerBrCasovaVezbiNedeljno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jSpinnerOstaliCasovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTxtDrugiObliciNastave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTxtStudijskiIstrazivackiRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(203, 203, 203)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAzuriraj)
                    .addComponent(jBtnSacuvaj)
                    .addComponent(jBtnObrisi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDodajNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajNastavnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDodajNastavnikaActionPerformed

    private void jBtnObrisiNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiNastavnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnObrisiNastavnikaActionPerformed

    private void jBtnDodajUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajUdzbenikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDodajUdzbenikActionPerformed

    private void jBtnObrisiUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiUdzbenikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnObrisiUdzbenikActionPerformed

    private void jBtnUnosStruktuiraniOblikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUnosStruktuiraniOblikActionPerformed
        JDialog fSadrzajStruktura = new FSadrzajStruktura(fMain, true);
        fSadrzajStruktura.setVisible(true);
    }//GEN-LAST:event_jBtnUnosStruktuiraniOblikActionPerformed

    private void jBtnUnosSadrzajaTekstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUnosSadrzajaTekstActionPerformed
        JDialog fSadrzajTekst = new FSadrzajTekst(FMain.getInstance(), true);
        fSadrzajTekst.setVisible(true);
    }//GEN-LAST:event_jBtnUnosSadrzajaTekstActionPerformed

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jTxtUdzbenikIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUdzbenikIdFocusLost
        try {

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTxtUdzbenikIdFocusLost

    private void JComboUdzbenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboUdzbenikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboUdzbenikActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> JComboUdzbenik;
    private javax.swing.JButton jBtnAzuriraj;
    private javax.swing.JButton jBtnDodajNastavnika;
    private javax.swing.JButton jBtnDodajUdzbenik;
    private javax.swing.JButton jBtnNoviUdzbenik;
    private javax.swing.JButton jBtnObrisi;
    private javax.swing.JButton jBtnObrisiNastavnika;
    private javax.swing.JButton jBtnObrisiUdzbenik;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JButton jBtnUnosSadrzajaTekst;
    private javax.swing.JButton jBtnUnosStruktuiraniOblik;
    private javax.swing.JComboBox<Object> jComboIzborNastavnika;
    private javax.swing.JComboBox<Object> jComboTipNastave;
    private javax.swing.JComboBox<Object> jComboTipNastaveSadrzaj;
    private javax.swing.JComboBox<Object> jComboVrstaINivoStudija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRezultatPretrage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerBrCasovaPredavanjaNedeljno;
    private javax.swing.JSpinner jSpinnerBrCasovaVezbiNedeljno;
    private javax.swing.JSpinner jSpinnerOstaliCasovi;
    private javax.swing.JTable jTblNastavnici;
    private javax.swing.JTable jTblUdzbenici;
    private javax.swing.JTextArea jTextAreaCilj;
    private javax.swing.JTextArea jTextAreaIshod;
    private javax.swing.JTextField jTxtDrugiObliciNastave;
    private javax.swing.JTextField jTxtNazivPredmeta;
    private javax.swing.JTextField jTxtStudijskiIstrazivackiRad;
    private javax.swing.JTextField jTxtUdzbenikId;
    private javax.swing.JTextField jTxtUslov;
    // End of variables declaration//GEN-END:variables

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void popuniVrstaINivoStudijaCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_VRSTE_I_NIVOE_STUDIJA, null);
            List<VrstaINivoStudija> vrsteStudija = (List<VrstaINivoStudija>) Kontroler.getInstance().primiOdgovor();

            for (VrstaINivoStudija vins : vrsteStudija) {
                jComboVrstaINivoStudija.addItem(vins);
            }

            jComboVrstaINivoStudija.setRenderer(new VrstaINivoStudijaRenderer());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void popuniTipNastaveCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_TIPOVE_NASTAVE, null);
            List<TipNastave> tipoviNastave = (List<TipNastave>) Kontroler.getInstance().primiOdgovor();

            for (TipNastave tipNastave : tipoviNastave) {
                jComboTipNastave.addItem(tipNastave);
                jComboTipNastaveSadrzaj.addItem(tipNastave);
            }

            jComboTipNastave.setRenderer(new TipNastaveRenderer());
            jComboTipNastaveSadrzaj.setRenderer(new TipNastaveRenderer());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dogodila se greska prilikom inicijalizacije combobox-a za tipove nastave.Greska:" + e.getMessage());
        }
    }

    private void popuniNastavniciCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_NASTAVNIKE, null);
            List<Nastavnik> nastavnici = (List<Nastavnik>) Kontroler.getInstance().primiOdgovor();

            for (Nastavnik nastavnik : nastavnici) {
                jComboIzborNastavnika.addItem(nastavnik);
            }

            jComboIzborNastavnika.setRenderer(new NastavnikRenderer());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dogodila se greska prilikom inicijalizacije combobox-a za nastavnike.Greska:" + e.getMessage());

        }
    }

    private void popuniUdzbeniciCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_UDZBENIKE, null);
            List<Udzbenik> udzbenici = (List<Udzbenik>) Kontroler.getInstance().primiOdgovor();

            for (Udzbenik udzbenik : udzbenici) {
                JComboUdzbenik.addItem(udzbenik);
            }
            JComboUdzbenik.setRenderer(new UdzbenikRenderer());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dogodila se greska prilikom inicijalizacije combobox-a za udzbenike.Greska:" + e.getMessage());

        }
    }

    private void inicijalizujTabeluNastavniciNaPredmetu() {
        try {

            TableModel nnptm = new NastavnikNaPredmetuTableModel(new ArrayList());
            jTblNastavnici.setModel(nnptm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dogodila se greska prilikom inicijalizacije table modela za nastavnike na predmetu.Greska:" + e.getMessage());

        }
    }

}
