/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Petar
 */
public class FSadrzajStruktura extends javax.swing.JDialog {

    /**
     * Creates new form FSadrzajStruktura
     */
    public FSadrzajStruktura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeSadrzaj = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jTxtNazivTematskeJedinice = new javax.swing.JTextField();
        jBtnDodajTematskuJedinicu = new javax.swing.JButton();
        jTxtNazivPodtematskeJedinice = new javax.swing.JTextField();
        jBtnDodajPodtematskuJedinicu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnDelete = new javax.swing.JButton();
        jBtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sadrzaj - struktura");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Sadrzaj");
        jTreeSadrzaj.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreeSadrzaj);

        jLabel1.setText("Naziv tematske jedinice:");

        jBtnDodajTematskuJedinicu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnDodajTematskuJedinicu.setText(">>");
        jBtnDodajTematskuJedinicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajTematskuJedinicuActionPerformed(evt);
            }
        });

        jBtnDodajPodtematskuJedinicu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnDodajPodtematskuJedinicu.setText(">>");
        jBtnDodajPodtematskuJedinicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajPodtematskuJedinicuActionPerformed(evt);
            }
        });

        jLabel2.setText("Naziv podtematske jedinice:");

        jBtnDelete.setText("Obrisi");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnSacuvaj.setText("Sacuvaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtNazivTematskeJedinice, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jBtnDodajTematskuJedinicu))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtNazivPodtematskeJedinice, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnDodajPodtematskuJedinicu)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNazivTematskeJedinice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDodajTematskuJedinicu))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNazivPodtematskeJedinice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDodajPodtematskuJedinicu))
                        .addGap(27, 27, 27)
                        .addComponent(jBtnDelete)
                        .addGap(98, 98, 98)
                        .addComponent(jBtnSacuvaj))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDodajTematskuJedinicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajTematskuJedinicuActionPerformed
        DefaultTreeModel dtm = (DefaultTreeModel) jTreeSadrzaj.getModel();
        DefaultMutableTreeNode koren = (DefaultMutableTreeNode) dtm.getRoot();

        String tematskaJedinica = jTxtNazivTematskeJedinice.getText();

        if (tematskaJedinica.trim().length() > 0) {
            koren.add(new DefaultMutableTreeNode(tematskaJedinica));
            jTxtNazivTematskeJedinice.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv tematske jedinice");
        }
    }//GEN-LAST:event_jBtnDodajTematskuJedinicuActionPerformed

    private void jBtnDodajPodtematskuJedinicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajPodtematskuJedinicuActionPerformed
        DefaultTreeModel dtm = (DefaultTreeModel) jTreeSadrzaj.getModel();
        DefaultMutableTreeNode selektovaniCvor = (DefaultMutableTreeNode) jTreeSadrzaj.getLastSelectedPathComponent();

        String podtematskaJedinicaNaziv = jTxtNazivPodtematskeJedinice.getText();
        if (podtematskaJedinicaNaziv.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv  podtematske jedinice");
            return;
        }

        if (selektovaniCvor != null) {
            if (!selektovaniCvor.isRoot()) {
                DefaultMutableTreeNode podtematskJedinica = new DefaultMutableTreeNode(podtematskaJedinicaNaziv);
                dtm.insertNodeInto(podtematskJedinica, selektovaniCvor, selektovaniCvor.getChildCount());
            } else {
                JOptionPane.showMessageDialog(this, "Izabrali ste koreni cvor. Morate izbrati konkretnu tematsku jedinicu! ");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Niste selektovali nijednu tematsku jedinicu! ");
        }


    }//GEN-LAST:event_jBtnDodajPodtematskuJedinicuActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        DefaultTreeModel dtm = (DefaultTreeModel) jTreeSadrzaj.getModel();
        DefaultMutableTreeNode selektovaniCvor = (DefaultMutableTreeNode) jTreeSadrzaj.getLastSelectedPathComponent();

        if (selektovaniCvor == null) {
            JOptionPane.showMessageDialog(this, "Niste selektovali nijednu tematsku jedinicu za brisanje");
            return;
        }

        if (selektovaniCvor.isRoot()) {
            JOptionPane.showMessageDialog(this, "Ne mozete izbrisati koreni element! ");
            return;
        }

        dtm.removeNodeFromParent(selektovaniCvor);
        

    }//GEN-LAST:event_jBtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnDodajPodtematskuJedinicu;
    private javax.swing.JButton jBtnDodajTematskuJedinicu;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeSadrzaj;
    private javax.swing.JTextField jTxtNazivPodtematskeJedinice;
    private javax.swing.JTextField jTxtNazivTematskeJedinice;
    // End of variables declaration//GEN-END:variables
}
