/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.PredmetNaStudijskomProgramu;
import domen.StudijskiProgram;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import kontroler.Kontroler;
import renderer.StudijskiProgramRenderer;
import table.model.PredmetNaStudijskomProgramuTableModel;
import transfer.util.IOperation;

/**
 *
 * @author Petar
 */
public class FSelectPredmetNaSmeru extends javax.swing.JDialog {

    /**
     * Creates new form FSelectPredmetNaSmeru
     */
    public FSelectPredmetNaSmeru(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        centrirajFormu();
        popuniStudijskiProgramiCombo();
        postaviTableModel();
        pripremiTabeluZaSortiranje();
        postaviBojuPozadine();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboStudijskiProgram = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNazivPredmeta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPredmetiNaSmeru = new javax.swing.JTable();
        jBtnPrikazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazite predmete na studijskom programu");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Izaberite studijski program:");

        jComboStudijskiProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboStudijskiProgramActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretrazite predmet na std programu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Unesite naziv predmeta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTxtNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTblPredmetiNaSmeru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblPredmetiNaSmeru);

        jBtnPrikazi.setBackground(new java.awt.Color(51, 204, 255));
        jBtnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPrikazi.setText("Prikazi");
        jBtnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboStudijskiProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnPrikazi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboStudijskiProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPrikazi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboStudijskiProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboStudijskiProgramActionPerformed
        try {
            StudijskiProgram sp = (StudijskiProgram) jComboStudijskiProgram.getSelectedItem();
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_PREDMETE_ZA_STUDIJSKI_PROGRAM, sp.getStudijskiProgramId());
            List<PredmetNaStudijskomProgramu> predmetiNaStudijskomProgramu = (List<PredmetNaStudijskomProgramu>) Kontroler.getInstance().primiOdgovor();

            if (jTblPredmetiNaSmeru.getModel() instanceof PredmetNaStudijskomProgramuTableModel) {
                PredmetNaStudijskomProgramuTableModel pnsptm = (PredmetNaStudijskomProgramuTableModel) jTblPredmetiNaSmeru.getModel();
                pnsptm.setPredmetiNaStudijskomProgramu(predmetiNaStudijskomProgramu);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>" + e.getMessage() + "</font></html>");
        }
    }//GEN-LAST:event_jComboStudijskiProgramActionPerformed

    private void jBtnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrikaziActionPerformed
        try {
            int red = jTblPredmetiNaSmeru.getSelectedRow();

            if (red >= 0) {
                PredmetNaStudijskomProgramuTableModel pnsptm = (PredmetNaStudijskomProgramuTableModel) jTblPredmetiNaSmeru.getModel();
                PredmetNaStudijskomProgramu predmet = pnsptm.getPredmetiNaStudijskomProgramu().get(red);
                dispose();

                JDialog fPredmetNaSmeru = new FPredmetNaSmeru(FMain.getInstance(), true, predmet);
                fPredmetNaSmeru.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>Niste selektovali nijedan predmet!</font></html>");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><font color=#ffffff>" + e.getMessage() + "</font></html>");
        }
    }//GEN-LAST:event_jBtnPrikaziActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    }//GEN-LAST:event_formMouseClicked

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPrikazi;
    private javax.swing.JComboBox<Object> jComboStudijskiProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblPredmetiNaSmeru;
    private javax.swing.JTextField jTxtNazivPredmeta;
    // End of variables declaration//GEN-END:variables

    private void postaviTableModel() {
        try {
            StudijskiProgram sp = (StudijskiProgram) jComboStudijskiProgram.getSelectedItem();
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_PREDMETE_ZA_STUDIJSKI_PROGRAM, sp.getStudijskiProgramId());
            List<PredmetNaStudijskomProgramu> predmetiNaStudijskomProgramu = (List<PredmetNaStudijskomProgramu>) Kontroler.getInstance().primiOdgovor();

            TableModel pnsp = new PredmetNaStudijskomProgramuTableModel(predmetiNaStudijskomProgramu);
            jTblPredmetiNaSmeru.setModel(pnsp);
        } catch (Exception ex) {

        }

    }

    private void popuniStudijskiProgramiCombo() {
        try {
            Kontroler.getInstance().posaljiZahtev(IOperation.VRATI_SVE_STUDIJSKE_PROGRAME, null);
            List<StudijskiProgram> studijskiProgrami = (List<StudijskiProgram>) Kontroler.getInstance().primiOdgovor();

            for (StudijskiProgram studijskiProgram : studijskiProgrami) {
                jComboStudijskiProgram.addItem(studijskiProgram);
            }

            jComboStudijskiProgram.setRenderer(new StudijskiProgramRenderer());
        } catch (Exception ex) {

        }

    }

    private void pripremiTabeluZaSortiranje() {
        try {
            TableRowSorter rowSorter = new TableRowSorter(jTblPredmetiNaSmeru.getModel());
            jTblPredmetiNaSmeru.setRowSorter(rowSorter);

            jTxtNazivPredmeta.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    String filterPredmet = jTxtNazivPredmeta.getText();

                    if (filterPredmet.length() == 0) {
                        rowSorter.setRowFilter(null);
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filterPredmet));
                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    String filterPredmet = jTxtNazivPredmeta.getText();

                    if (filterPredmet.length() == 0) {
                        rowSorter.setRowFilter(null);
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filterPredmet));
                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
        } catch (Exception ex) {

        }

    }

    private void postaviBojuPozadine() {
        this.getContentPane().setBackground(new java.awt.Color(51, 0, 102));
    }

}
